package com.beesinergi.model;

import java.util.Date;

public class AppParameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_parameter.pk_app_parameter
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    private Integer pkAppParameter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_parameter.description
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_parameter.name
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_parameter.data_type
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_parameter.is_viewable
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    private String isViewable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_parameter.changed_date
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    private Date changedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_parameter.changed_by
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    private String changedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_parameter.value
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_parameter.pk_app_parameter
     *
     * @return the value of app_parameter.pk_app_parameter
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public Integer getPkAppParameter() {
        return pkAppParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_parameter.pk_app_parameter
     *
     * @param pkAppParameter the value for app_parameter.pk_app_parameter
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public void setPkAppParameter(Integer pkAppParameter) {
        this.pkAppParameter = pkAppParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_parameter.description
     *
     * @return the value of app_parameter.description
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_parameter.description
     *
     * @param description the value for app_parameter.description
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_parameter.name
     *
     * @return the value of app_parameter.name
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_parameter.name
     *
     * @param name the value for app_parameter.name
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_parameter.data_type
     *
     * @return the value of app_parameter.data_type
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_parameter.data_type
     *
     * @param dataType the value for app_parameter.data_type
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_parameter.is_viewable
     *
     * @return the value of app_parameter.is_viewable
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public String getIsViewable() {
        return isViewable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_parameter.is_viewable
     *
     * @param isViewable the value for app_parameter.is_viewable
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public void setIsViewable(String isViewable) {
        this.isViewable = isViewable == null ? null : isViewable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_parameter.changed_date
     *
     * @return the value of app_parameter.changed_date
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public Date getChangedDate() {
        return changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_parameter.changed_date
     *
     * @param changedDate the value for app_parameter.changed_date
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_parameter.changed_by
     *
     * @return the value of app_parameter.changed_by
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public String getChangedBy() {
        return changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_parameter.changed_by
     *
     * @param changedBy the value for app_parameter.changed_by
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy == null ? null : changedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_parameter.value
     *
     * @return the value of app_parameter.value
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_parameter.value
     *
     * @param value the value for app_parameter.value
     *
     * @mbggenerated Thu Sep 03 16:26:17 ICT 2015
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}