package com.beesinergi.model;

import java.util.Date;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.pk_category
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Integer pkCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String changedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Date changedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.remarks
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.pk_category
     *
     * @return the value of category.pk_category
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Integer getPkCategory() {
        return pkCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.pk_category
     *
     * @param pkCategory the value for category.pk_category
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setPkCategory(Integer pkCategory) {
        this.pkCategory = pkCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.created_by
     *
     * @return the value of category.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.created_by
     *
     * @param createdBy the value for category.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.created_date
     *
     * @return the value of category.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.created_date
     *
     * @param createdDate the value for category.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.changed_by
     *
     * @return the value of category.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getChangedBy() {
        return changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.changed_by
     *
     * @param changedBy the value for category.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy == null ? null : changedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.changed_date
     *
     * @return the value of category.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Date getChangedDate() {
        return changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.changed_date
     *
     * @param changedDate the value for category.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.remarks
     *
     * @return the value of category.remarks
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.remarks
     *
     * @param remarks the value for category.remarks
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.is_active
     *
     * @return the value of category.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.is_active
     *
     * @param isActive the value for category.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }
}