package com.beesinergi.model;

import java.util.Date;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.pk_department
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Integer pkDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_code
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String changedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Date changedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.pk_department
     *
     * @return the value of department.pk_department
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Integer getPkDepartment() {
        return pkDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.pk_department
     *
     * @param pkDepartment the value for department.pk_department
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setPkDepartment(Integer pkDepartment) {
        this.pkDepartment = pkDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_code
     *
     * @return the value of department.department_code
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_code
     *
     * @param departmentCode the value for department.department_code
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_name
     *
     * @return the value of department.department_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_name
     *
     * @param departmentName the value for department.department_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.created_by
     *
     * @return the value of department.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.created_by
     *
     * @param createdBy the value for department.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.created_date
     *
     * @return the value of department.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.created_date
     *
     * @param createdDate the value for department.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.changed_by
     *
     * @return the value of department.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getChangedBy() {
        return changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.changed_by
     *
     * @param changedBy the value for department.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy == null ? null : changedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.changed_date
     *
     * @return the value of department.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Date getChangedDate() {
        return changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.changed_date
     *
     * @param changedDate the value for department.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.is_active
     *
     * @return the value of department.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.is_active
     *
     * @param isActive the value for department.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }
}