package com.beesinergi.model;

import java.util.Date;

public class Unit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.pk_unit
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Integer pkUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.unit_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String changedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Date changedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.remarks
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.pk_unit
     *
     * @return the value of unit.pk_unit
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Integer getPkUnit() {
        return pkUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.pk_unit
     *
     * @param pkUnit the value for unit.pk_unit
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setPkUnit(Integer pkUnit) {
        this.pkUnit = pkUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.unit_name
     *
     * @return the value of unit.unit_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.unit_name
     *
     * @param unitName the value for unit.unit_name
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.created_by
     *
     * @return the value of unit.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.created_by
     *
     * @param createdBy the value for unit.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.created_date
     *
     * @return the value of unit.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.created_date
     *
     * @param createdDate the value for unit.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.changed_by
     *
     * @return the value of unit.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getChangedBy() {
        return changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.changed_by
     *
     * @param changedBy the value for unit.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy == null ? null : changedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.changed_date
     *
     * @return the value of unit.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Date getChangedDate() {
        return changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.changed_date
     *
     * @param changedDate the value for unit.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.remarks
     *
     * @return the value of unit.remarks
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.remarks
     *
     * @param remarks the value for unit.remarks
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.is_active
     *
     * @return the value of unit.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.is_active
     *
     * @param isActive the value for unit.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }
}