package com.beesinergi.model;

import java.util.Date;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.pk_user_role
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Integer pkUserRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.fk_role
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Integer fkRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.fk_user
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Integer fkUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String changedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private Date changedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    private String isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.pk_user_role
     *
     * @return the value of user_role.pk_user_role
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Integer getPkUserRole() {
        return pkUserRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.pk_user_role
     *
     * @param pkUserRole the value for user_role.pk_user_role
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setPkUserRole(Integer pkUserRole) {
        this.pkUserRole = pkUserRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.fk_role
     *
     * @return the value of user_role.fk_role
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Integer getFkRole() {
        return fkRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.fk_role
     *
     * @param fkRole the value for user_role.fk_role
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setFkRole(Integer fkRole) {
        this.fkRole = fkRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.fk_user
     *
     * @return the value of user_role.fk_user
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Integer getFkUser() {
        return fkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.fk_user
     *
     * @param fkUser the value for user_role.fk_user
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setFkUser(Integer fkUser) {
        this.fkUser = fkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.created_by
     *
     * @return the value of user_role.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.created_by
     *
     * @param createdBy the value for user_role.created_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.created_date
     *
     * @return the value of user_role.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.created_date
     *
     * @param createdDate the value for user_role.created_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.changed_by
     *
     * @return the value of user_role.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getChangedBy() {
        return changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.changed_by
     *
     * @param changedBy the value for user_role.changed_by
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy == null ? null : changedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.changed_date
     *
     * @return the value of user_role.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public Date getChangedDate() {
        return changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.changed_date
     *
     * @param changedDate the value for user_role.changed_date
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.is_active
     *
     * @return the value of user_role.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.is_active
     *
     * @param isActive the value for user_role.is_active
     *
     * @mbggenerated Mon Nov 02 22:27:25 ICT 2015
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }
}